export const Constants = {
  //USER_SIGNIN_REQUESTS
  USER_SIGNIN_REQUEST: "USER_SIGNIN_REQUEST",
  USER_SIGNIN_SUCCESS: "USER_SIGNIN_SUCCESS",
  USER_SIGNIN_FAIL: "USER_SIGNIN_FAIL",

  //USER_SIGNOUT_REQUEST
  USER_SIGNOUT: "USER_SIGNOUT",
  //CREATE NEW POST
  POSTS_CREATE_REQUEST: "POSTS_CREATE_REQUEST",
  POSTS_CREATE_SUCCESS: "POSTS_CREATE_SUCCESS",
  POSTS_CREATE_FAIL: "POSTS_CREATE_FAIL",
  //FETCH POST
  POSTS_FETCH_REQUEST: "POSTS_FETCH_REQUEST",
  POSTS_FETCH_SUCCESS: "POSTS_FETCH_SUCCESS",
  POSTS_FETCH_FAIL: "POSTS_FETCH_FAIL",
  //LIKE POST
  POSTS_LIKE_REQUEST: "POSTS_LIKE_REQUEST",
  POSTS_LIKE_SUCCESS: "POSTS_LIKE_SUCCESS",
  POSTS_LIKE_FAIL: "POSTS_LIKE_FAIL",
  //DELETE POST
  POSTS_DELETE_REQUEST: "POSTS_DELETE_REQUEST",
  POSTS_DELETE_SUCCESS: "POSTS_DELETE_SUCCESS",
  POSTS_DELETE_FAIL: "POSTSDELETEE_FAIL",
  //FETCH SELECTED USER
  SELECTED_USER_FETCH_REQUEST: "SELECTED_USER_FETCH_REQUEST",
  SELECTED_USER_FETCH_SUCCESS: "SELECTED_USER_FETCH_SUCCESS",
  SELECTED_USER_FETCH_FAIL: "SELECTED_USER_FETCH_FAIL",
  //FETCH SELECTED USER POSTS
  SELECTED_USER_POSTS_REQUEST: "SELECTED_USER_POSTS_REQUEST",
  SELECTED_USER_POSTS_SUCCESS: "SELECTED_USER_POSTS_SUCCESS",
  SELECTED_USER_POSTS_FAIL: "SELECTED_USER_POSTS_FAIL",
  //USER FOLLOWERS REQUEST
  USER_FOLLOWERS_REQUEST: "USER_FOLLOWERS_REQUEST",
  USER_FOLLOWERS_SUCCESS: "USER_FOLLOWERS_SUCCESS",
  USER_FOLLOWERS_FAIL: "USER_FOLLOWERS_FAIL",
  //FETCH SELECTED POST
  SELECTED_POST_FETCH_REQUEST: "SELECTED_POST_FETCH_REQUEST",
  SELECTED_POST_FETCH_SUCCESS: "SELECTED_POST_FETCH_SUCCESS",
  SELECTED_POST_FETCH_FAIL: "SELECTED_POST_FETCH_FAIL",
  //FETCH COMMENTS
  FETCH_COMMENTS_OF_POST_REQUEST: "FETCH_COMMENTS_OF_POST_REQUEST",
  FETCH_COMMENTS_OF_POST_SUCCESS: "FETCH_COMMENTS_OF_POST_SUCCESS",
  FETCH_COMMENTS_OF_POST_FAIL: "FETCH_COMMENTS_OF_POST_FAIL",
  //CREATE CREATE_COMMENTS
  CREATE_COMMENTS_REQUEST: "CREATE_COMMENTS_REQUEST",
  CREATE_COMMENTS_SUCCESS: "CREATE_COMMENTS_SUCCESS",
  CREATE_COMMENTS_FAIL: "CREATE_COMMENTS_FAIL",
};
